version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "08:00"
      timezone: "Asia/Taipei"
    # Disable all pull requests for Docker dependencies
    open-pull-requests-limit: 0
    commit-message:
      prefix: "[Bot]"
      include: "scope"